# -*- coding: utf-8 -*-
"""Netflix_Content_Strategy_2023.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgEdA65K7Ofq0of6tFtHBXeq5OpBbz1m

# **Netflix Content Strategy Analysis**

# Defining the Objectives

Main Objective:

Analyze how content type, release timing (season/day), and language influence Netflix's viewership strategy.

Sub-Objectives:

Identify the most frequent content types (e.g., movies vs TV shows).

Analyze release trends by day of the week and season.

Understand the role of language in content distribution.

Provide insights on how Netflix might optimize releases for maximum engagement.

# Loading and Understanding the Dataset
"""

# Import libraries
import pandas as pd

# Load the dataset
file_path = 'netflix_content_2023.csv'
df = pd.read_csv(file_path)

# Basic info about the dataset
print(" Dataset Information:")
print(df.info())

# Preview first 5 rows
print("\n First 5 Rows:")
print(df.head())

# Check for missing values
print("\n❗ Missing Values per Column:")
print(df.isnull().sum())

# Check for unique values per column
print("\n Unique Values per Column:")
print(df.nunique())

"""# Data cleaning process"""

# 1. Drop duplicate rows if any
df = df.drop_duplicates()

df.columns

# 2. Rename columns for clarity (optional but recommended)
df.rename(columns={
    'Available Globally?': 'Available_Globally',
    'Release Date': 'Release_Date',
    'Hours Viewed': 'Hours_Viewed',
    'Content Type': 'Content_Type',
    'Language Indicator': 'Language'
}, inplace=True)
df.columns

# 3. Convert Release_Date to datetime
df['Release_Date'] = pd.to_datetime(df['Release_Date'], errors='coerce')
df['Release_Date']

# 4. Clean and convert Hours_Viewed
df['Hours_Viewed'] = df['Hours_Viewed'].astype(str).str.replace(',', '', regex=False).astype('int64')
df['Hours_Viewed']

# 5. Standardize categorical fields
df['Content_Type'] = df['Content_Type'].str.strip().str.title()
df['Language'] = df['Language'].str.strip().str.title()

# 6. Extract release day and season
df['Release_Day'] = df['Release_Date'].dt.day_name()
df['Release_Season'] = df['Release_Date'].dt.month % 12 // 3
season_map = {0: 'Winter', 1: 'Spring', 2: 'Summer', 3: 'Fall'}
df['Release_Season'] = df['Release_Season'].map(season_map)

# 7. Check cleaned data
print(df.head())

"""# Exploratory Data Analysis (EDA) and Visualization

1️⃣ Content Type Distribution
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Content Type Count
plt.figure(figsize=(6,4))
sns.countplot(data=df, x='Content_Type', palette='Set3')
plt.title('Content Type Distribution')
plt.xlabel('Content Type')
plt.ylabel('Count')
plt.show()

"""2️⃣ Language Distribution (Top 10 Languages)"""

top_languages = df['Language'].value_counts().head(7)

plt.figure(figsize=(10,5))
sns.barplot(x=top_languages.values, y=top_languages.index, palette='viridis')
plt.title('Top 10 Languages in Netflix Content (2023)')
plt.xlabel('Count')
plt.ylabel('Language')
plt.show()

"""3️⃣ Content Released by Season"""

plt.figure(figsize=(6,4))
sns.countplot(data=df, x='Release_Season', hue='Content_Type', palette='coolwarm')
plt.title('Content Release by Season')
plt.xlabel('Season')
plt.ylabel('Count')
plt.legend(title='Content Type')
plt.show()

"""4️⃣ Content Released by Day of the Week"""

day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
plt.figure(figsize=(8,5))
sns.countplot(data=df, x='Release_Day', order=day_order, hue='Content_Type', palette='Accent')
plt.title('Content Release by Day of the Week')
plt.xlabel('Day of Week')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.legend(title='Content Type')
plt.show()

"""5️⃣ Top 10 Most Viewed Titles"""

top_titles = df.sort_values('Hours_Viewed', ascending=False).head(10)

plt.figure(figsize=(10,6))
sns.barplot(y=top_titles['Title'], x=top_titles['Hours_Viewed'], palette='magma')
plt.title('Top 10 Most Viewed Titles (2023)')
plt.xlabel('Hours Viewed')
plt.ylabel('Title')
plt.show()

"""#  Insights & Recommendations"""

from IPython.display import display, Markdown

# --- Step 1: Key Insights ---

insights = [
    "**Content Type Focus**: Shows dominate over movies, suggesting Netflix leverages episodic content for sustained engagement.",
    "**Release Timing**: Fridays and Thursdays are the most frequent release days, aligned with weekend viewer peaks.",
    "**Seasonality**: Winter and Spring see more content drops, potentially targeting holidays and school breaks.",
    "**Language Strategy**: English is most common, but non-English titles (e.g., Korean, Spanish) also show strong presence.",
    "**High Engagement Titles**: Top viewed titles often come from franchises or high-recognition series."
]

# --- Step 2: Strategic Recommendations ---

recommendations = [
    "**Content Type**: Double down on successful series and consider follow-ups or spin-offs for high-engagement shows.",
    "**Release Day Strategy**: Continue leveraging Thursday/Friday releases; test mid-week launches for regional optimization.",
    "**Seasonal Strategy**: Concentrate big releases around Winter, Spring, and holidays to maximize binge potential.",
    "**Language Expansion**: Localize content through dubbing/subtitles and promote culturally resonant regional content.",
    "**Marketing**: Enhance campaign planning around known IPs using teaser strategies and post-launch promotions."
]

# --- Display Output in Markdown Format ---

display(Markdown("## 🔍 Key Insights"))
for insight in insights:
    display(Markdown(f"- {insight}"))

display(Markdown("## 💡 Strategic Recommendations"))
for rec in recommendations:
    display(Markdown(f"- {rec}"))